# site settings
title: HELPBUTTON.nl
email: email@mail.io
description: Alarmeer eenvoudig met een druk op de knop hulp wanneer het nodig is
baseurl: ""
permalink: pretty

# collection
collections:
  faqs:
    output: true
